apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-service3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3-db
  template:
    metadata:
      labels:
        app: service3-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "29042002Sa"
            - name: MYSQL_DATABASE
              value: "service3_db"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc-service3
---
apiVersion: v1
kind: Service
metadata:
  name: service3-db
spec:
  selector:
    app: service3-db
  ports:
    - port: 3306
      targetPort: 3306
