openapi: 3.0.3
info:
  title: API REST - TFG WebApp
  description: API REST para la gesti贸n de atletas, entrenadores, eventos, disciplinas y equipamiento.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Servidor de desarrollo

paths:
  ###  AUTENTICACIN ###
  /api/auth/login:
    post:
      summary: Iniciar sesi贸n
      tags:
        - Autenticaci贸n
      responses:
        "200":
          description: Inicio de sesi贸n exitoso.

  /api/auth/logout:
    post:
      summary: Cerrar sesi贸n
      tags:
        - Autenticaci贸n
      responses:
        "200":
          description: Cierre de sesi贸n exitoso.

  ###  USUARIOS ###
  /api/users/me:
    get:
      summary: Obtener usuario autenticado
      tags:
        - Usuarios
      responses:
        "200":
          description: Datos del usuario autenticado.

  ###  EVENTOS ###
  /api/events:
    get:
      summary: Obtener eventos
      tags:
        - Eventos
      responses:
        "200":
          description: Lista de eventos obtenida correctamente.

    post:
      summary: Crear evento
      tags:
        - Eventos
      responses:
        "201":
          description: Evento creado exitosamente.

  ###  ATLETAS ###
  /api/athletes:
    get:
      summary: Obtener atletas
      tags:
        - Atletas
      responses:
        "200":
          description: Lista de atletas obtenida correctamente.

    post:
      summary: Crear un atleta
      tags:
        - Atletas
      responses:
        "201":
          description: Atleta creado exitosamente.

  ###  ENTRENADORES ###
  /api/coaches:
    get:
      summary: Obtener entrenadores
      tags:
        - Entrenadores
      responses:
        "200":
          description: Lista de entrenadores obtenida correctamente.

    post:
      summary: Crear un entrenador
      tags:
        - Entrenadores
      responses:
        "201":
          description: Entrenador creado exitosamente.

  ###  RESULTADOS ###
  /api/results:
    get:
      summary: Obtener resultados de eventos
      tags:
        - Resultados
      responses:
        "200":
          description: Lista de resultados obtenida correctamente.

    post:
      summary: Crear un resultado
      tags:
        - Resultados
      responses:
        "201":
          description: Resultado creado exitosamente.

  ###  DISCIPLINAS ###
  /api/disciplines:
    get:
      summary: Obtener disciplinas
      tags:
        - Disciplinas
      responses:
        "200":
          description: Lista de disciplinas obtenida correctamente.

    post:
      summary: Crear una disciplina
      tags:
        - Disciplinas
      responses:
        "201":
          description: Disciplina creada exitosamente.

  /api/disciplines/{id}:
    get:
      summary: Obtener una disciplina por ID
      tags:
        - Disciplinas
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Disciplina encontrada.
        "404":
          description: Disciplina no encontrada.

    put:
      summary: Actualizar disciplina
      tags:
        - Disciplinas
      responses:
        "200":
          description: Disciplina actualizada correctamente.

    delete:
      summary: Eliminar disciplina
      tags:
        - Disciplinas
      responses:
        "204":
          description: Disciplina eliminada correctamente.

  ###  EQUIPAMIENTO ###
  /api/equipment:
    get:
      summary: Obtener equipamiento
      tags:
        - Equipamiento
      responses:
        "200":
          description: Lista de equipamiento obtenida correctamente.

    post:
      summary: Crear equipamiento
      tags:
        - Equipamiento
      responses:
        "201":
          description: Equipamiento creado exitosamente.

  /api/equipment/{id}:
    get:
      summary: Obtener equipamiento por ID
      tags:
        - Equipamiento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Equipamiento encontrado.
        "404":
          description: Equipamiento no encontrado.

    put:
      summary: Actualizar equipamiento
      tags:
        - Equipamiento
      responses:
        "200":
          description: Equipamiento actualizado correctamente.

    delete:
      summary: Eliminar equipamiento
      tags:
        - Equipamiento
      responses:
        "204":
          description: Equipamiento eliminado correctamente.

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        date:
          type: string
          format: date

    Athlete:
      type: object
      properties:
        licenseNumber:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        discipline:
          type: string

    Coach:
      type: object
      properties:
        licenseNumber:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        disciplines:
          type: array
          items:
            type: string

    Discipline:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        coaches:
          type: array
          items:
            type: string

    Equipment:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
