apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq-storage
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  kind: managed
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
