apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
spec:
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:3.12-management