apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1-backend
  template:
    metadata:
      labels:
        app: service1-backend
    spec:
      containers:
        - name: service1-backend
          image: saac04/service1-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          envFrom:
            - configMapRef:
                name: service1-config
            - secretRef:
                name: service1-secrets
