apiVersion: v1
kind: Service
metadata:
  name: service1-backend
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "30"
spec:
  selector:
    app: service1-backend
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: https
      protocol: TCP
      port: 9091
      targetPort: 9091
  type: LoadBalancer
