name: CD Pipeline 

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  build-and-deploy:
    name: Build & Deploy Docker Image
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: docker login 
            -u "saac04" -p "29042002Sa" 

      - name: Build Docker Image
        run: |
          docker build -t saac04/backend:latest -f docker/Dockerfile_backend .

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag saac04/backend:latest saac04/backend:latest
          docker push saac04/backend:latest

      - name: Start Application with Docker Compose
        run: |
          cd docker
          docker-compose up -d

      - name: Verify Running Containers
        run: docker ps -a
