name: CI Pipeline

on:
  workflow_dispatch:
  #pull_request:
    #branches:
      #- main

jobs:
  setup-and-test:
    name: Setup, Build & Test All Modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ----------------------------
      # Java / Maven setup
      # ----------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ----------------------------
      # Install shared-protos
      # ----------------------------
      - name: Install shared-protos
        working-directory: shared-protos
        run: mvn clean install

      # ----------------------------
      # Run tests for Service1 
      # ----------------------------
      - name: Run tests - Service1
        working-directory: service1-backend
        run: mvn clean verify -DexcludeTags=integration

      # ----------------------------
      # Run tests for Service2
      # ----------------------------
      - name: Run tests - Service2 (Results/PDF)
        working-directory: Service2-Results-PDF
        run: mvn clean verify -DexcludeTags=integration

      # ----------------------------
      # Run tests for Service3
      # ----------------------------
      - name: Run tests - Service3 (Events)
        working-directory: Service3-Events
        run: mvn clean verify -DexcludeTags=integration

      # ----------------------------
      # Node / Angular setup
      # ----------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Angular unit tests
        working-directory: frontend
        run: npm test -- --watch=false --browsers=ChromeHeadless

      # ----------------------------
      # SonarCloud Analysis
      # ----------------------------
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: 4dd5c6a7ea10044d985b5bf2ff03c431625e8088
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="https://sonarcloud.io" \
            -e SONAR_TOKEN="${SONAR_TOKEN}" \
            -e SONAR_ORGANIZATION="codeurjc-students" \
            -e SONAR_PROJECT_KEY="codeurjc-students_2024-AtletismoMostoles" \
            -v "${{ github.workspace }}:/usr/src" \
            -w "/usr/src" \
            sonarsource/sonar-scanner-cli:latest \
            -Dsonar.projectBaseDir=.

