name: CI Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    name: Setup and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ----------------------------
      # Start backend with Docker Compose
      # ----------------------------
      - name: Check Docker installation
        run: |
          docker --version
          docker info

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Bring up containers
        run: |
          cd docker
          docker-compose up -d

      - name: Wait for backend to start
        run: sleep 15

      - name: List running containers
        run: docker ps -a

      - name: Test backend connectivity
        run: curl -k https://localhost:443/api/auth/login || echo "Cannot connect to backend"

      # ----------------------------
      # Java / Maven setup
      # ----------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ----------------------------
      # Run backend tests + JaCoCo
      # ----------------------------
      - name: Run Maven verify (with JaCoCo)
        working-directory: backend
        run: mvn clean verify

      # ----------------------------
      # Angular Frontend
      # ----------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Angular unit tests and collect coverage
        working-directory: frontend
        run: npm ci && npm test

      # ----------------------------
      # SonarCloud Analysis via Docker
      # ----------------------------
      - name: Run SonarScanner in Docker
        env:
          SONAR_TOKEN: 4dd5c6a7ea10044d985b5bf2ff03c431625e8088
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="https://sonarcloud.io" \
            -e SONAR_TOKEN="${SONAR_TOKEN}" \
            -e SONAR_ORGANIZATION="codeurjc-students" \
            -e SONAR_PROJECT_KEY="codeurjc-students_2024-AtletismoMostoles" \
            -v "${{ github.workspace }}:/usr/src" \
            -w "/usr/src" \
            sonarsource/sonar-scanner-cli:latest
