name: CI - Tests y Análisis Sonar

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Test Backend y Frontend + Sonar
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # --- Instalar módulo compartido shared-protos ---
      - name: Instalar shared-protos localmente
        working-directory: shared-protos
        run: mvn clean install

      # --- Test de cada backend con Jacoco ---
      - name: Test Service1 + Jacoco
        working-directory: service1-backend
        run: mvn clean verify -Dspring.profiles.active=test

      - name: Test Service2 + Jacoco
        working-directory: Service2-Results-PDF
        run: mvn clean verify -Dspring.profiles.active=test

      - name: Test Service3 + Jacoco
        working-directory: Service3-Events
        run: mvn clean verify -Dspring.profiles.active=test

      # --- Configurar Node para el frontend ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias frontend
        working-directory: frontend
        run: npm ci

      - name: Ejecutar tests Angular con cobertura
        working-directory: frontend
        run: npm run test:ci

      # --- Enviar a SonarCloud ---
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: 4dd5c6a7ea10044d985b5bf2ff03c431625e8088
