name: CI Pipeline

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CD Pipeline"]
    types:
      - completed
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    name: Setup and Run Tests
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Iniciar servicio Docker en Windows
        run: |
          Start-Service docker
          Get-Service docker

      - name: Verificar Docker en GitHub Actions
        run: |
          docker --version
          docker info

      - name: Instalar Docker Compose
        run: |
          Invoke-WebRequest -Uri "https://github.com/docker/compose/releases/latest/download/docker-compose-windows-x86_64.exe" -OutFile "C:\Program Files\Docker\docker-compose.exe"
          [Environment]::SetEnvironmentVariable("Path", $Env:Path + ";C:\\Program Files\\Docker", [System.EnvironmentVariableTarget]::Machine)

      - name: Iniciar los contenedores con Docker Compose
        run: |
          cd docker
          docker-compose up -d

      - name: Esperar que el backend se inicie
        run: Start-Sleep -Seconds 15

      - name: Listar todos los contenedores en ejecución
        run: docker ps -a

      - name: Probar conexión al backend en el contenedor
        run: |
          Invoke-WebRequest -Uri "https://localhost:443/api/auth/login" -UseBasicParsing || echo "No se pudo conectar"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run API REST Tests with Maven
        run: |
          cd backend
          mvn clean test -Dtest="com.example.TFG_WebApp.API_REST_TESTs.**"

      - name: Run E2E Tests with Maven
        run: |
          cd backend
          mvn clean test -Dtest="com.example.TFG_WebApp.E2E_TESTs.**"
