name: CI Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    name: Setup and Run Tests
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ----------------------------
      # Start backend with Docker Compose
      # ----------------------------
      - name: Check Docker installation
        run: |
          docker --version
          docker info

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Bring up containers
        run: |
          cd docker
          docker-compose up -d

      - name: Wait for backend to start
        run: sleep 15

      - name: List running containers
        run: docker ps -a

      - name: Test backend connectivity
        run: curl -k https://localhost:443/api/auth/login || echo "Cannot connect to backend"

      # ----------------------------
      # Java / Maven setup
      # ----------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # ----------------------------
      # Install Chrome & ChromeDriver for Selenium E2E
      # ----------------------------
      - name: Install Google Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          wget -q "https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set ChromeDriver environment variables
        run: |
          echo "webdriver.chrome.driver=/usr/local/bin/chromedriver" >> $GITHUB_ENV
          echo "WEBDRIVER_CHROME_DRIVER=/usr/local/bin/chromedriver" >> $GITHUB_ENV

      - name: Configure headless Chrome options
        if: runner.os == 'Linux'
        run: |
          echo "CHROME_OPTIONS=--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --window-size=1920,1080" >> $GITHUB_ENV

      - name: Verify Chrome & ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version

      # ----------------------------
      # Run all backend tests (unit, REST API, and E2E)
      # ----------------------------
      - name: Run Backend Tests
        run: |
          cd backend
          mvn clean test \
            -Dtest="com.example.TFG_WebApp.Unit_TESTs.*,com.example.TFG_WebApp.API_REST_TESTs.*,com.example.TFG_WebApp.E2E_TESTs.*"

      # ----------------------------
      # Angular Frontend
      # ----------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Angular unit tests
        working-directory: frontend
        run: npm test -- --watch=false --browsers=ChromeHeadless