name: CI Pipeline

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CD Pipeline"]
    types:
      - completed
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    name: Setup and Run Tests
    runs-on: ubuntu-latest  # Cambiamos de Windows a Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verificar Docker en GitHub Actions
        run: |
          docker --version
          docker info

      - name: Iniciar los contenedores con Docker Compose
        run: |
          cd docker
          docker-compose up -d

      - name: Esperar que el backend se inicie
        run: sleep 15  # En Linux, usamos 'sleep'

      - name: Listar todos los contenedores en ejecución
        run: docker ps -a

      - name: Probar conexión al backend en el contenedor
        run: curl -k https://localhost:443/api/auth/login || echo "No se pudo conectar"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run API REST Tests with Maven
        run: |
          cd backend
          mvn clean test -Dtest="com.example.TFG_WebApp.API_REST_TESTs.**"

      - name: Run E2E Tests with Maven
        run: |
          cd backend
          mvn clean test -Dtest="com.example.TFG_WebApp.E2E_TESTs.**"
