name: CI Pipeline

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "CD Pipeline" ]
    types:
      - completed
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    name: Setup and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      ##- name: Run Docker Upgrade Script
      ##  run: |
      ##    .\upgrade_docker.bat

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Listar contenedores en ejecución
        run: docker ps

      - name: Run API REST Tests with Maven
        run: |
          cd backend
          mvn clean test -Dtest="com.example.TFG_WebApp.API_REST_TESTs.**"


      - name: Run E2E Tests with Maven
        run: |
          cd backend
          mvn clean test -Dtest="com.example.TFG_WebApp.E2E_TESTs.**"
